/run/verbose 1
/run/printProgress 1000
#/event/verbose 1
#/tracking/verbose 1

##Specify output file
/analysis/setOutputFormat hdf5
/analysis/setFileName X17

##Set Volume ID's for Geometry Volumes (volume.in.geometry.file volID)
/geometry/setVolID bege 1

##to track all steps, including steps for which Edep=0
/tracking/recordAllSteps

##initialize the run
/generator/setDecayMode x17
/run/initialize
/process/em/printParameters

# print volIDs
/geometry/listPhysVols

/run/beamOn 100000
